### ISSUE TITLE
Stuff that other stuff is stuffed with

### ISSUE THREAD

**Issue by PhoenixICE** [QuiCM/EssentialsPlus#1]
Things requested for total replacement of MAC and Essentials:

These are commands that are used by me often:
- [x] up/down/left/right {number}
  Moves user that many places in direction specified
- [ ] kill [-a] {name*} [reason]
  Kills players, make sure to calculate how much damage needed to kill player, -a switch is auto (don't need separate command) - run against user twice to remove auto killing, allow wildcard \* for all players
- [x] emute {name*} [reason]
  Mutes players, regardless of if they log on or off, allow wildcard \* for all players
- [x] findperm {command}
  Lists commands for permission, please make sure to return all permissions (incase command collision)
- [x] find {(i)tem/(n)pc} {name}
  Looks up item/npc id based on switch
- [ ] butcher [-h/-a] [distance]
  Kills all npcs within range of distance, -h = hostile only, -a = all npcs
- [ ] heal {name*}
  heals player, or wildcard \* for all players
- [ ] ghost
  Removes player, and reconnects them after using command again
- [x] freezetime
- [ ] disable {name*} [reason]
  Disables user or all users using wildcard *
- [x] ruler [1/2]
  Calculates the distance between two points
- [x] kickall [reason]
  Kicks all players without permission to not be kicked
- [x] sethome [name] | myhome [name]
  same as previous version
- [x] =
  same as previous version
- [x] sudo {player} {command}
  same as previous version
- [ ] nick [nick]
  same as previous version (make sure to check whether they can talk prior to sending)
- [ ] invsee [name | -restore | -force]
  same as previous, -force changes the players inventory that got invsee'd, to what was changed by the person who invsee'd them
- [ ] give any permission the ability to not be affected by them

**Comment by bippity** [comment]
Should +1 or something to these lines: https://github.com/WhiteXZ/EssentialsPlus/blob/master/EssentialsPlus/Commands.cs#L573-L574
Right now, it's excluding the first/last block. 
Ex: A wall is 25 blocks high, 3 blocks wide. The ruler command will say that X: 2 and Y: 24. This will confuse a player who's trying to build.
