### ISSUE TITLE
Back history (/b) is not updated when a player dies

### ISSUE THREAD

**Issue by AxisKriel** [QuiCM/EssentialsPlus#9]
Looks like a player's BackHistory is no longer being updated when they die. The `/back` command is still capable of tracking it properly when warp commands are involved.

The most likely cause would be the addition of a new PlayerDeath [118] packet that is now used instead of packet 45. I don't know if they've deprecated No. 45 or not, but simply handling [this new packet](https://tshock.readme.io/docs/multiplayer-packet-structure#section-playerdeathv2-118-) to do the same thing will probably do.

https://github.com/WhiteXZ/EssentialsPlus/blob/master/EssentialsPlus/EssentialsPlus.cs#L352-L357

**Comment by dkstanner** [comment]
I know this has been long dead, however I have submitted some PRs (#12 #13) that should solve this issue. Thank you for pointing me in the right direction here.

**Comment by QuiCM** [comment]
Resolved by @dkstanner in #13
